FROM maven:3.9-eclipse-temurin-17 AS build

WORKDIR /app
COPY app/pom.xml .
COPY app/src ./src
RUN mvn clean package -Dmaven.test.skip=true

FROM eclipse-temurin:17

WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]