FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
COPY ledger/pom.xml .
RUN mvn dependency:go-offline -B
COPY ledger/src ./src
RUN mvn clean package -Dmaven.test.skip=true -Dmaven.compiler.forceJavacCompilerUse=true

FROM eclipse-temurin:17
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8082
CMD ["java", "-jar", "app.jar"]