spring.application.name=ledger-service
# PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres:5432/pagamento?currentSchema=ledger
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
# Porta
server.port=8082
# Filas
ledger.queue.saque-iniciado=ledger.saque.iniciado
ledger.queue.pix-confirmado=ledger.pix.confirmado
ledger.queue.pix-falhou=ledger.pix.falhou
ledger.queue.credito-inicial=ledger.credito.inicial