spring:
  datasource:
    url: jjdbc:mysql://mysql:3306/ledger-db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080
