spring.application.name=transaction-service

# PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres:5432/pagamento?currentSchema=transaction
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.default_schema=transaction
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Porta
server.port=8080

# Integração com ledger
ledger.base-url=http://ledger-service:8082

# Exchange
app.rabbit.exchange=ledger.exchange

# Routing keys publicadas pelo transaction-service
app.rabbit.routing-key.credito-inicial=ledger.credito.inicial
app.rabbit.routing-key.saque-iniciado=ledger.saque.iniciado

# Routing keys consumidas do ledger
app.rabbit.routing-key.ledger-debited=ledger.debited
app.rabbit.routing-key.ledger-debit-confirmed=ledger.debit.confirmed
app.rabbit.routing-key.ledger-reversed=ledger.reversed

# Filas consumidas pelo transaction-service
app.rabbit.queue.ledger-debited=transaction.ledger.debited
app.rabbit.queue.ledger-debit-confirmed=transaction.ledger.debit.confirmed
app.rabbit.queue.ledger-reversed=transaction.ledger.reversed